### ISSUE TITLE
lua errors

### ISSUE THREAD

**Issue by SilverSaw** [eavidaze/wow-addon-per-hour#3]
6x StartXPPerHour: Couldn't find relative frame: $parentDetails
2x ToggleReputationPerHour: Couldn't find relative frame: $parentDetails
2x ToggleExperiencePerHour: Couldn't find relative frame: $parentDetails
2x ToggleHonorPerHour: Couldn't find relative frame: $parentDetails

**Comment by eavidaze** [comment]
Thanks for reporting! I'll work on it soon.

**Comment by eavidaze** [comment]
After a lot of research and testing, I found that the error is in the template `UIGoldBorderButtonTemplate` that I chose for my buttons!

Reference:
- https://www.wowinterface.com/forums/showthread.php?t=56452

**Comment by eavidaze** [comment]
@SilverSaw could you please check if these errors no longer happen in the new version?

It's available on CurseForge.

**Comment by SilverSaw** [comment]
Just checked, everything works great now, no errors, thank you for the fast response.
